### ISSUE TITLE
ACT1 Ana Kimberly Hernández Pérez 1° B

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Anakimberly#1]
![Mapa mental (1)](https://user-images.githubusercontent.com/112224202/187828174-ec135e31-5a64-4d67-b12a-c466c84c8328.png)

**Comment by AmeliReyesHernandez** [comment]
18.4 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
